global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'insighthub-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'insighthub-api'
    scrape_interval: 5s
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'

